/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Organization;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationRecord extends UpdatableRecordImpl<OrganizationRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Organization.id</code>.
     */
    public OrganizationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.Organization.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Organization.name</code>.
     */
    public OrganizationRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.Organization.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.Organization.inn</code>.
     */
    public OrganizationRecord setInn(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.Organization.inn</code>.
     */
    public String getInn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.Organization.checking_acc</code>.
     */
    public OrganizationRecord setCheckingAcc(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.Organization.checking_acc</code>.
     */
    public String getCheckingAcc() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Organization.ORGANIZATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Organization.ORGANIZATION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Organization.ORGANIZATION.INN;
    }

    @Override
    public Field<String> field4() {
        return Organization.ORGANIZATION.CHECKING_ACC;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getInn();
    }

    @Override
    public String component4() {
        return getCheckingAcc();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getInn();
    }

    @Override
    public String value4() {
        return getCheckingAcc();
    }

    @Override
    public OrganizationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrganizationRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public OrganizationRecord value3(String value) {
        setInn(value);
        return this;
    }

    @Override
    public OrganizationRecord value4(String value) {
        setCheckingAcc(value);
        return this;
    }

    @Override
    public OrganizationRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationRecord
     */
    public OrganizationRecord() {
        super(Organization.ORGANIZATION);
    }

    /**
     * Create a detached, initialised OrganizationRecord
     */
    public OrganizationRecord(Integer id, String name, String inn, String checkingAcc) {
        super(Organization.ORGANIZATION);

        setId(id);
        setName(name);
        setInn(inn);
        setCheckingAcc(checkingAcc);
    }
}
