/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Waybill;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillRecord extends UpdatableRecordImpl<WaybillRecord> implements Record3<Integer, Date, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Waybill.id</code>.
     */
    public WaybillRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Waybill.date</code>.
     */
    public WaybillRecord setDate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill.date</code>.
     */
    public Date getDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.Waybill.organization_id</code>.
     */
    public WaybillRecord setOrganizationId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Date, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Date, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Waybill.WAYBILL.ID;
    }

    @Override
    public Field<Date> field2() {
        return Waybill.WAYBILL.DATE;
    }

    @Override
    public Field<Integer> field3() {
        return Waybill.WAYBILL.ORGANIZATION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Date component2() {
        return getDate();
    }

    @Override
    public Integer component3() {
        return getOrganizationId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Date value2() {
        return getDate();
    }

    @Override
    public Integer value3() {
        return getOrganizationId();
    }

    @Override
    public WaybillRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WaybillRecord value2(Date value) {
        setDate(value);
        return this;
    }

    @Override
    public WaybillRecord value3(Integer value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public WaybillRecord values(Integer value1, Date value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillRecord
     */
    public WaybillRecord() {
        super(Waybill.WAYBILL);
    }

    /**
     * Create a detached, initialised WaybillRecord
     */
    public WaybillRecord(Integer id, Date date, Integer organizationId) {
        super(Waybill.WAYBILL);

        setId(id);
        setDate(date);
        setOrganizationId(organizationId);
    }
}
