/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.WaybillItems;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillItemsRecord extends UpdatableRecordImpl<WaybillItemsRecord> implements Record5<Integer, Integer, Integer, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Waybill_items.item_id</code>.
     */
    public WaybillItemsRecord setItemId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill_items.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Waybill_items.waybill_id</code>.
     */
    public WaybillItemsRecord setWaybillId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill_items.waybill_id</code>.
     */
    public Integer getWaybillId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.Waybill_items.quantity</code>.
     */
    public WaybillItemsRecord setQuantity(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.Waybill_items.nomenclature</code>.
     */
    public WaybillItemsRecord setNomenclature(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill_items.nomenclature</code>.
     */
    public Integer getNomenclature() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.Waybill_items.price</code>.
     */
    public WaybillItemsRecord setPrice(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.Waybill_items.price</code>.
     */
    public Double getPrice() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return WaybillItems.WAYBILL_ITEMS.ITEM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return WaybillItems.WAYBILL_ITEMS.WAYBILL_ID;
    }

    @Override
    public Field<Integer> field3() {
        return WaybillItems.WAYBILL_ITEMS.QUANTITY;
    }

    @Override
    public Field<Integer> field4() {
        return WaybillItems.WAYBILL_ITEMS.NOMENCLATURE;
    }

    @Override
    public Field<Double> field5() {
        return WaybillItems.WAYBILL_ITEMS.PRICE;
    }

    @Override
    public Integer component1() {
        return getItemId();
    }

    @Override
    public Integer component2() {
        return getWaybillId();
    }

    @Override
    public Integer component3() {
        return getQuantity();
    }

    @Override
    public Integer component4() {
        return getNomenclature();
    }

    @Override
    public Double component5() {
        return getPrice();
    }

    @Override
    public Integer value1() {
        return getItemId();
    }

    @Override
    public Integer value2() {
        return getWaybillId();
    }

    @Override
    public Integer value3() {
        return getQuantity();
    }

    @Override
    public Integer value4() {
        return getNomenclature();
    }

    @Override
    public Double value5() {
        return getPrice();
    }

    @Override
    public WaybillItemsRecord value1(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public WaybillItemsRecord value2(Integer value) {
        setWaybillId(value);
        return this;
    }

    @Override
    public WaybillItemsRecord value3(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public WaybillItemsRecord value4(Integer value) {
        setNomenclature(value);
        return this;
    }

    @Override
    public WaybillItemsRecord value5(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public WaybillItemsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillItemsRecord
     */
    public WaybillItemsRecord() {
        super(WaybillItems.WAYBILL_ITEMS);
    }

    /**
     * Create a detached, initialised WaybillItemsRecord
     */
    public WaybillItemsRecord(Integer itemId, Integer waybillId, Integer quantity, Integer nomenclature, Double price) {
        super(WaybillItems.WAYBILL_ITEMS);

        setItemId(itemId);
        setWaybillId(waybillId);
        setQuantity(quantity);
        setNomenclature(nomenclature);
        setPrice(price);
    }
}
