/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organization implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String  name;
    private final String  inn;
    private final String  checkingAcc;

    public Organization(Organization value) {
        this.id = value.id;
        this.name = value.name;
        this.inn = value.inn;
        this.checkingAcc = value.checkingAcc;
    }

    public Organization(
        Integer id,
        String  name,
        String  inn,
        String  checkingAcc
    ) {
        this.id = id;
        this.name = name;
        this.inn = inn;
        this.checkingAcc = checkingAcc;
    }

    /**
     * Getter for <code>public.Organization.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.Organization.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.Organization.inn</code>.
     */
    public String getInn() {
        return this.inn;
    }

    /**
     * Getter for <code>public.Organization.checking_acc</code>.
     */
    public String getCheckingAcc() {
        return this.checkingAcc;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organization (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(inn);
        sb.append(", ").append(checkingAcc);

        sb.append(")");
        return sb.toString();
    }
}
