/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waybill implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Date    date;
    private final Integer organizationId;

    public Waybill(Waybill value) {
        this.id = value.id;
        this.date = value.date;
        this.organizationId = value.organizationId;
    }

    public Waybill(
        Integer id,
        Date    date,
        Integer organizationId
    ) {
        this.id = id;
        this.date = date;
        this.organizationId = organizationId;
    }

    /**
     * Getter for <code>public.Waybill.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.Waybill.date</code>.
     */
    public Date getDate() {
        return this.date;
    }

    /**
     * Getter for <code>public.Waybill.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return this.organizationId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Waybill (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(organizationId);

        sb.append(")");
        return sb.toString();
    }
}
