/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillItems implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer itemId;
    private final Integer waybillId;
    private final Integer quantity;
    private final Integer nomenclature;
    private final Double  price;

    public WaybillItems(WaybillItems value) {
        this.itemId = value.itemId;
        this.waybillId = value.waybillId;
        this.quantity = value.quantity;
        this.nomenclature = value.nomenclature;
        this.price = value.price;
    }

    public WaybillItems(
        Integer itemId,
        Integer waybillId,
        Integer quantity,
        Integer nomenclature,
        Double  price
    ) {
        this.itemId = itemId;
        this.waybillId = waybillId;
        this.quantity = quantity;
        this.nomenclature = nomenclature;
        this.price = price;
    }

    /**
     * Getter for <code>public.Waybill_items.item_id</code>.
     */
    public Integer getItemId() {
        return this.itemId;
    }

    /**
     * Getter for <code>public.Waybill_items.waybill_id</code>.
     */
    public Integer getWaybillId() {
        return this.waybillId;
    }

    /**
     * Getter for <code>public.Waybill_items.quantity</code>.
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Getter for <code>public.Waybill_items.nomenclature</code>.
     */
    public Integer getNomenclature() {
        return this.nomenclature;
    }

    /**
     * Getter for <code>public.Waybill_items.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WaybillItems (");

        sb.append(itemId);
        sb.append(", ").append(waybillId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(nomenclature);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
