/*
 * This file is generated by jOOQ.
 */
package db.tables.daos;


import db.tables.Waybill;
import db.tables.records.WaybillRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillDao extends DAOImpl<WaybillRecord, db.tables.pojos.Waybill, Integer> {

    /**
     * Create a new WaybillDao without any configuration
     */
    public WaybillDao() {
        super(Waybill.WAYBILL, db.tables.pojos.Waybill.class);
    }

    /**
     * Create a new WaybillDao with an attached configuration
     */
    public WaybillDao(Configuration configuration) {
        super(Waybill.WAYBILL, db.tables.pojos.Waybill.class, configuration);
    }

    @Override
    public Integer getId(db.tables.pojos.Waybill object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<db.tables.pojos.Waybill> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Waybill.WAYBILL.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<db.tables.pojos.Waybill> fetchById(Integer... values) {
        return fetch(Waybill.WAYBILL.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public db.tables.pojos.Waybill fetchOneById(Integer value) {
        return fetchOne(Waybill.WAYBILL.ID, value);
    }

    /**
     * Fetch records that have <code>date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<db.tables.pojos.Waybill> fetchRangeOfDate(Date lowerInclusive, Date upperInclusive) {
        return fetchRange(Waybill.WAYBILL.DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date IN (values)</code>
     */
    public List<db.tables.pojos.Waybill> fetchByDate(Date... values) {
        return fetch(Waybill.WAYBILL.DATE, values);
    }

    /**
     * Fetch records that have <code>organization_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<db.tables.pojos.Waybill> fetchRangeOfOrganizationId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Waybill.WAYBILL.ORGANIZATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>organization_id IN (values)</code>
     */
    public List<db.tables.pojos.Waybill> fetchByOrganizationId(Integer... values) {
        return fetch(Waybill.WAYBILL.ORGANIZATION_ID, values);
    }
}
