/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.FlywaySchemaHistory;
import db.tables.Nomenclature;
import db.tables.Organization;
import db.tables.Waybill;
import db.tables.WaybillItems;
import db.tables.records.FlywaySchemaHistoryRecord;
import db.tables.records.NomenclatureRecord;
import db.tables.records.OrganizationRecord;
import db.tables.records.WaybillItemsRecord;
import db.tables.records.WaybillRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<NomenclatureRecord> NOMENCLATURE_PK = Internal.createUniqueKey(Nomenclature.NOMENCLATURE, DSL.name("Nomenclature_pk"), new TableField[] { Nomenclature.NOMENCLATURE.NOMENCLATURE_ID }, true);
    public static final UniqueKey<OrganizationRecord> ORGANIZATION_PK = Internal.createUniqueKey(Organization.ORGANIZATION, DSL.name("Organization_pk"), new TableField[] { Organization.ORGANIZATION.ID }, true);
    public static final UniqueKey<WaybillRecord> WAYBILL_PK = Internal.createUniqueKey(Waybill.WAYBILL, DSL.name("Waybill_pk"), new TableField[] { Waybill.WAYBILL.ID }, true);
    public static final UniqueKey<WaybillItemsRecord> WAYBILL_ITEMS_PK = Internal.createUniqueKey(WaybillItems.WAYBILL_ITEMS, DSL.name("Waybill_items_pk"), new TableField[] { WaybillItems.WAYBILL_ITEMS.ITEM_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WaybillRecord, OrganizationRecord> WAYBILL__WAYBILL_FK0 = Internal.createForeignKey(Waybill.WAYBILL, DSL.name("Waybill_fk0"), new TableField[] { Waybill.WAYBILL.ORGANIZATION_ID }, Keys.ORGANIZATION_PK, new TableField[] { Organization.ORGANIZATION.ID }, true);
    public static final ForeignKey<WaybillItemsRecord, WaybillRecord> WAYBILL_ITEMS__WAYBILL_ITEMS_FK0 = Internal.createForeignKey(WaybillItems.WAYBILL_ITEMS, DSL.name("Waybill_items_fk0"), new TableField[] { WaybillItems.WAYBILL_ITEMS.WAYBILL_ID }, Keys.WAYBILL_PK, new TableField[] { Waybill.WAYBILL.ID }, true);
    public static final ForeignKey<WaybillItemsRecord, NomenclatureRecord> WAYBILL_ITEMS__WAYBILL_ITEMS_FK1 = Internal.createForeignKey(WaybillItems.WAYBILL_ITEMS, DSL.name("Waybill_items_fk1"), new TableField[] { WaybillItems.WAYBILL_ITEMS.NOMENCLATURE }, Keys.NOMENCLATURE_PK, new TableField[] { Nomenclature.NOMENCLATURE.NOMENCLATURE_ID }, true);
}
