/*
 * This file is generated by jOOQ.
 */
package db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.Organization_id_seq</code>
     */
    public static final Sequence<Integer> ORGANIZATION_ID_SEQ = Internal.createSequence("Organization_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Waybill_id_seq</code>
     */
    public static final Sequence<Integer> WAYBILL_ID_SEQ = Internal.createSequence("Waybill_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Waybill_items_item_id_seq</code>
     */
    public static final Sequence<Integer> WAYBILL_ITEMS_ITEM_ID_SEQ = Internal.createSequence("Waybill_items_item_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
